#tuple
data=(1,2,3,4,5)
data2=("a","b","c","d")
data3=1,2,3
print(type(data))
print(type(data2))
print(type(data3))
print(dir(data))
print(data2.count("c"))
print(data2.index("c"))
print(data2[3])
data2=1,2,3,4,5,6
print(type(data2))
