#set
#data={1,2,3,3,4}

'''
print(type(data))
print(data)
print(dir(data))
#data.add(7)
#print(data)
#data.clear()
#print(data)
data2=data.copy()
print(data2)
print(data)
'''
#difference
#fruits={"apple","banana","orange"}
#company={"google","facebook","apple"}
#cmp=fruits.difference(company)
#print(cmp)
#fruits=company.difference(fruits)
#print(fruits)
#discard
#data={"apple","banana","ornage"}
#data.discard("apple")
#print(data)

#intersection
#comm=fruits.intersection(company)
#print(comm)
#print(fruits&company)
#union
#union_data=fruits.union(company)
#print(union_data)

#union
#data1={"abc","dfh","sds"}
#data2={"123","456","789","098"}
#data3=data1.union(data2)
#print(data3)
#update
a={"a","b","c","k"}
b={"k","j","i","p"}
#a.update(b)
#print(a)
a.pop()
print(a)
